### ISSUE TITLE
Scrierea corecta

### ISSUE THREAD

**Issue by empet** [emanuelcovaci/Demografie#10]
In Readme trebuie scris Tehnologii  folosite (NU Tehnologi)!!!

**Comment by emanuelcovaci** [comment]
Exact asta am scris

**Comment by empet** [comment]
NU ati scris asa, ci cu un singur i si trebuie DOI  de i. Se spune _tehnologii_, nu _tehnologi_,  _fii serios,_ nu _fi serios_.
